#!/usr/bin/env ruby
$-v = nil
STDOUT.sync = STDIN.sync = true
require 'sunburst'

def help
	puts <<~EOF
		Sunburst lets you run a command for a given time.
		When the time expires, the program will be SIGKILLed.
		Sunburst will then report the total CPU time and last known memory usage
		of the program.

		If no time is specified, it will run until the command exits.

		Arguments:
		\s\s\s\s--time=N\s\s\s\s\s\s\s\s\s\sRun the program for N seconds
		\s\s\s\s-h | --help\s\s\s\s\s\s\sShow this help section
		\s\s\s\s--humanize\s\s\s\s\s\s\s\sHuman readable memory units

		Example:
		\s\s\s\ssunburst echo hello world --time=0.05 --humanize
		\s\s\s\ssunburst "echo hello world" --time=0.05 --humanize
		\s\s\s\ssunburst "ruby -e 'while true do end'" --time=3 --humanize
		\s\s\s\ssunburst "ruby -e 'p :Hello'" --time=3 --humanize
	EOF

	exit 0
end

def splitter(sub = 8)
	width = Sunburst.win_width
	puts ?\n, ?-.*(width - sub).center(width)
end

help if ARGV.any? { |x| x[/^\-(\-help|h)$/] }

time_arg = ARGV.find { |x| x[/^\-\-time=[0-9]+\.?[0-9]*$/] }
ARGV.delete(time_arg) if time_arg
time = time_arg ? time_arg.split('=')[-1].to_f : nil

_human_readable = ARGV.find { |x| x[/^\-\-humanize$/] }
ARGV.delete(_human_readable) if _human_readable
human_readable = _human_readable

command = ARGV.join(' ')

help if command.empty?

puts %Q(:: Running "#{command}" for #{time || 'infinite'} seconds)


begin
	print ""

	message = "\e[4mLogging Standard Output and Error\e[0m"
	puts "\e[38;2;243;156;18m#{message.center(Sunburst.win_width + 6)}\e[0m"

	data = Sunburst.measure(command: command, time: time, sleep_time: 0.0001)
	print "\e[38;2;243;156;18m"
	splitter()
	print "\e[0m"

	exec_time = data[:execution_time]
	cpu_time = data[:cpu_time]
	percent_time = cpu_time.*(100).fdiv(exec_time)

	style = "\e[1;"
	style << if percent_time > 75
		"38;2;230;80;70m"
	elsif percent_time > 50
		"38;2;45;125;255m"
	elsif percent_time > 25
		"38;2;255;225;0m"
	else
		"38;2;40;175;95m"
	end

	puts ":: Total Execution Time: #{data[:execution_time]} seconds\e[0m"
	puts ":: CPU Time: #{style}#{data[:cpu_time]}\e[0m second#{?s if data[:cpu_time] != 1}"

	mem = data[:memory]
	if mem
		percent_mem = mem.*(100).fdiv(Sunburst.total_ram)

		style = "\e[1;"
		style << if percent_mem > 50
			"38;2;230;80;70m"
		elsif percent_mem > 30
			"38;2;45;125;255m"
		elsif percent_mem > 10
			"38;2;255;225;0m"
		else
			"38;2;40;175;95m"
		end

		if human_readable
			mem_text = if mem >= 10 ** 12
				"#{mem.fdiv(10 ** 12).round(3)} TB"
			elsif mem >= 10 ** 9
				"#{mem.fdiv(10 ** 9).round(3)} GB"
			elsif mem >= 10 ** 6
				"#{mem.fdiv(10 ** 6).round(3)} MB"
			elsif mem >= 10 ** 3
				"#{mem.fdiv(10 ** 3).round(3)} KB"
			else
				"#{mem} Bytes"
			end

			puts ":: Memory usage: #{style}#{mem_text}\e[0m"
		else
			puts ":: Memory usage: #{style}#{mem} bytes\e[0m"
		end
	else
		puts ":: The memory usage can't be logged."
	end

	max_threads = data[:max_threads]
	style = "\e[1;"
	style << if max_threads > 16
		"38;2;230;80;70m"
	elsif max_threads > 8
		"38;2;45;125;255m"
	elsif max_threads > 4
		"38;2;255;225;0m"
	else
		"38;2;40;175;95m"
	end

	puts ":: Max Threads: #{style}#{max_threads}\e[0m"

rescue Errno::ENOENT
	puts "sunburst: #{command}: command not found"
	puts ?\n, ?- * Sunburst.win_width
rescue StandardError
	puts $!.full_message
end
